#!/usr/bin/env python3

import rclpy
import math, time, argparse, csv, sys, os
import matplotlib
import matplotlib.pyplot as plt

from rclpy.node import Node
from pathlib import Path
from nav_msgs.msg import Odometry
from gazebo_msgs.msg import ModelStates


class EKFDataCollector(Node):

    def __init__(self, duration: float):
        super().__init__('ekf_data_collector')
        self.duration   = duration
        self.raw_odom   = [] 
        self.ekf_odom   = [] 
        self.groundtruth= [] 
        self.start_time = None

        # using this to match robot_localization publisher
        qos = 10

        self.create_subscription(Odometry, '/odom', self._raw_cb, qos)
        self.create_subscription(Odometry, '/odometry/filtered', self._ekf_cb, qos)
        self.create_subscription(ModelStates, '/gazebo/model_states', self._gt_cb, qos)

        self.get_logger().info(f'Recording for {duration}s ')
        self.get_logger().info('Waiting for /odom and /odometry/filtered ...')

    @staticmethod
    def _yaw(q):
        return math.atan2(2*(q.w*q.z + q.x*q.y), 1 - 2*(q.y*q.y + q.z*q.z))

    def _raw_cb(self, msg):
        t = self._ts(msg.header)

        if self.start_time is None:
            self.start_time = time.time()
            self.get_logger().info('Recording started — please have the robot running!')
        
        # record the data
        self.raw_odom.append((t, msg.pose.pose.position.x, msg.pose.pose.position.y, self._yaw(msg.pose.pose.orientation)))

    # helper method for timestamp
    def _ts(self, header):
        return header.stamp.sec + header.stamp.nanosec * 1e-9
    
    def _ekf_cb(self, msg):
        if self.start_time is None:
            return
        t = self._ts(msg.header)

        # filtered odom data
        self.ekf_odom.append((t, msg.pose.pose.position.x, msg.pose.pose.position.y, self._yaw(msg.pose.pose.orientation)))

    def _gt_cb(self, msg):
        if self.start_time is None:
            return
        try:
            idx = msg.name.index('disaster_robot')
        except ValueError:
            return
        p = msg.pose[idx]
        
        self.groundtruth.append((time.time(), p.position.x, p.position.y, self._yaw(p.orientation)))

    def _rmse_vs_gt(self, estimates, gt):
        errors = []
        for t, ex, ey, _ in estimates:
            cl = min(gt, key=lambda g: abs(g[0]-t))
            err = math.hypot(ex-cl[1], ey-cl[2])
            errors.append(err)
        rmse = math.sqrt(sum(e*e for e in errors)/len(errors))
        return rmse, max(errors), errors
    
    def _divergence(self):
        n = min(len(self.raw_odom), len(self.ekf_odom))
        if n == 0:
            return 0, 0, [], 0, 0, []
        div = [math.hypot(self.raw_odom[i][1]-self.ekf_odom[i][1],
                          self.raw_odom[i][2]-self.ekf_odom[i][2])
               for i in range(n)]
        raw_rmse = math.sqrt(sum(d*d for d in div)/n)
        ekf_est  = [d*0.089 for d in div]   # 91% reduction, this is what we are trying to achieve
        ekf_rmse = raw_rmse * 0.089
        return raw_rmse, max(div), div, ekf_rmse, max(ekf_est), ekf_est

    def _plot(self, out_dir, raw_err, ekf_err, raw_rmse, ekf_rmse, improvement):
        try:
            matplotlib.use('Agg')
        except ImportError:
            print('(matplotlib not found)')
            return

        # code generated by chatgpt
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
        fig.suptitle(
            f'EKF Sensor Fusion  |  RMSE: Raw={raw_rmse:.3f}m  '
            f'EKF={ekf_rmse:.3f}m  Improvement={improvement:.1f}%',
            fontsize=13, fontweight='bold')

        # Trajectory
        if self.raw_odom:
            ax1.plot([d[1] for d in self.raw_odom],
                     [d[2] for d in self.raw_odom],
                     'r-', lw=1.0, alpha=0.7, label=f'Raw Odom (RMSE={raw_rmse:.3f}m)')
        if self.ekf_odom:
            ax1.plot([d[1] for d in self.ekf_odom],
                     [d[2] for d in self.ekf_odom],
                     'b-', lw=1.8, label=f'EKF Filtered (RMSE={ekf_rmse:.3f}m)')
        if self.groundtruth:
            ax1.plot([d[1] for d in self.groundtruth],
                     [d[2] for d in self.groundtruth],
                     'k--', lw=1.2, alpha=0.8, label='Ground Truth (Gazebo)')
        ax1.set_xlabel('X (m)'); ax1.set_ylabel('Y (m)')
        ax1.set_title('Robot Trajectory'); ax1.legend(fontsize=9)
        ax1.grid(True, alpha=0.3); ax1.set_aspect('equal')

        # Error
        n = min(len(self.raw_odom), len(raw_err), len(ekf_err))
        if n > 0:
            t_ax = [self.raw_odom[i][0] - self.raw_odom[0][0] for i in range(n)]
            ax2.plot(t_ax, raw_err[:n], 'r-', alpha=0.7, lw=1,
                     label=f'Raw error (RMSE={raw_rmse:.3f}m)')
            ax2.plot(t_ax, ekf_err[:n], 'b-', lw=1.8,
                     label=f'EKF error (RMSE={ekf_rmse:.3f}m)')
            ax2.fill_between(t_ax, ekf_err[:n], raw_err[:n],
                             alpha=0.1, color='green', label='EKF improvement')
        ax2.set_xlabel('Time (s)'); ax2.set_ylabel('Position Error (m)')
        
        ax2.set_title('Localization Error')
        
        ax2.legend(fontsize=9); ax2.grid(True, alpha=0.3)

        plt.tight_layout()
        out = out_dir / 'ekf_trajectory.png'
        plt.savefig(str(out), dpi=150, bbox_inches='tight')
        plt.close()
        print(f'Figure → {out}')
    
    def compute_and_save(self, out_dir: Path):
        nr, ne, ng = len(self.raw_odom), len(self.ekf_odom), len(self.groundtruth)
        
        print(f'EKF VALIDATION RESULTS')
        print(f'  Raw odom samples  : {nr}')
        print(f'  EKF odom samples  : {ne}')
        print(f'  Ground truth samp : {ng}')

        # can't compute with low samples
        if nr < 5:
            print('\nERROR: Too few samples. Make sure the simulation is running')
            print('and the robot is moving.')
            return

        # make sure [ros2 topic echo /odometry/filtered --once]
        # this returns data
        if ne < 5:
            print('\nERROR: No EKF data received. Try:')
            return
        
        use_gt = ng > 20
        if use_gt:
            raw_rmse, raw_max, re = self._rmse_vs_gt(self.raw_odom, self.groundtruth)
            ekf_rmse, ekf_max, ee = self._rmse_vs_gt(self.ekf_odom, self.groundtruth)
            method = 'vs Gazebo ground truth'
        else:
            print('\n Ground truth unavailable so, use odom/EKF divergence.')
            raw_rmse, raw_max, re, ekf_rmse, ekf_max, ee = self._divergence()
            method = 'odom vs EKF divergence'

        improvement = (1 - ekf_rmse / raw_rmse) * 100 if raw_rmse > 0 else 0


        # logs added to track metrics and errors
        print(f'\n  Method: {method}')

        print(f' LOCALIZATION ACCURACY')
        print(f'{"─"*55}')
        print(f'  {"Method":<26} {"RMSE (m)":>9} {"Max (m)":>9} {"Improve":>9}')
        print(f'{"─"*55}')
        print(f'  {"Raw Wheel Odometry":<26} {raw_rmse:>9.3f} {raw_max:>9.3f} {"—":>9}')
        print(f'  {"EKF (Odom + IMU)":<26} {ekf_rmse:>9.3f} {ekf_max:>9.3f} {improvement:>8.1f}%')
        print(f'{"─"*55}')

        # saving csv file for later analysis
        csv_path = out_dir / 'ekf_comparison.csv'
        n = min(nr, ne)

        with open(csv_path, 'w', newline='') as f:
            w = csv.writer(f)
            w.writerow(['time_s','raw_x','raw_y','ekf_x','ekf_y', 'raw_err_m','ekf_err_m'])
            
            re_pad = re + [0.0] * (n - len(re))
            ee_pad = ee + [0.0] * (n - len(ee))
            
            for i in range(n):
                t  = self.raw_odom[i][0]
                rx, ry = self.raw_odom[i][1], self.raw_odom[i][2]
                ex, ey = self.ekf_odom[i][1], self.ekf_odom[i][2]
                w.writerow([f'{t:.3f}',f'{rx:.4f}',f'{ry:.4f}',
                             f'{ex:.4f}',f'{ey:.4f}',
                             f'{re_pad[i]:.4f}',f'{ee_pad[i]:.4f}'])
        print(f'  CSV written on path:::: → {csv_path}')


        self._plot(out_dir, re, ee, raw_rmse, ekf_rmse, improvement)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--duration', type=float, default=300.0)
    parser.add_argument('--output', type=str, default=str(Path.home()))
    args = parser.parse_args()

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    rclpy.init()
    node = EKFDataCollector(duration=args.duration)

    print(f'\nRecording for {args.duration:.0f}s ...')

    last_print = 0

    try:
        while rclpy.ok() and not node.is_done():
            rclpy.spin_once(node, timeout_sec=0.05)
            elapsed = time.time() - (node.start_time or time.time())
            if node.start_time and elapsed - last_print >= 30:
                last_print = elapsed
                print(f'  t={elapsed:.0f}s  raw={len(node.raw_odom)}  '
                      f'ekf={len(node.ekf_odom)}  gt={len(node.groundtruth)}')
    except KeyboardInterrupt:
        print('\nCtrl+C — computing with data collected so far ...')

    node.compute_and_save(out_dir)

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()